<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="M5-D-CXNNX52" name="com.salesforce.automation.test.AccountContractTestUsingTestNG" tests="2" failures="1" timestamp="8 May 2019 05:37:50 GMT" time="118.893" errors="0">
  <testcase name="test_AccountSearchPage" time="66.276" classname="com.salesforce.automation.test.AccountContractTestUsingTestNG">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:94)
	at com.salesforce.automation.test.AccountContractTestUsingTestNG.test_AccountSearchPage(AccountContractTestUsingTestNG.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test_AccountSearchPage -->
  <testcase name="test_AccountSearchPage" time="52.617" classname="com.salesforce.automation.test.AccountContractTestUsingTestNG"/>
</testsuite> <!-- com.salesforce.automation.test.AccountContractTestUsingTestNG -->
