<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="M5-D-CXNNX52" name="com.salesforce.automation.test.RepointingOpeningSWStartPageTest" tests="46" failures="16" timestamp="30 Aug 2019 11:06:03 GMT" time="2991.726" errors="0">
  <testcase name="test_RepointingOpeningSWStartPage" time="82.129" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="59.660" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="60.166" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="66.551" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="57.103" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="58.635" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="55.915" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="58.256" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="76.820" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="64.461" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="66.754" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="66.315" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="65.622" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="65.880" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="69.099" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="67.864" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="65.586" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="67.320" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="68.474" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="68.488" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="64.193" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="68.180" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="68.673" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="77.551" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="67.883" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="61.201" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="65.281" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="66.237" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="66.273" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="67.707" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="55.415" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="64.799" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="36.751" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodWithParent(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)">
      <![CDATA[java.lang.AssertionError: Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodWithParent(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="79.986" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="68.821" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="38.178" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodNotObtainedWithoutNull(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)">
      <![CDATA[java.lang.AssertionError: Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodNotObtainedWithoutNull(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="67.775" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="66.438" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="81.552" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="57.065" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="67.808" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="67.331" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="69.506" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : null">
      <![CDATA[java.lang.AssertionError: Test Failed due to : null
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="81.544" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
  <testcase name="test_RepointingOpeningSWStartPage" time="36.752" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest">
    <failure type="java.lang.AssertionError" message="Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodNotObtainedWithNull(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)">
      <![CDATA[java.lang.AssertionError: Test Failed due to : com.salesforce.automation.pageModel.RepointingOpeningSWStartPage.validatePayMethodNotObtainedWithNull(com.salesforce.automation.datamodel.RepointingOpeningSWStartDataModel)
	at org.testng.Assert.fail(Assert.java:93)
	at com.salesforce.automation.test.RepointingOpeningSWStartPageTest.test_RepointingOpeningSWStartPage(RepointingOpeningSWStartPageTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_RepointingOpeningSWStartPage -->
  <testcase name="test_RepointingOpeningSWStartPage" time="67.728" classname="com.salesforce.automation.test.RepointingOpeningSWStartPageTest"/>
</testsuite> <!-- com.salesforce.automation.test.RepointingOpeningSWStartPageTest -->
